namespace PhotoWoo.Localization;

public static class MainTranslations
{
    // Each row uses the same locale order; key coverage is checked at startup.
    private static readonly string[] Languages = ["en", "ru", "de", "fr", "es", "it", "pt", "pl", "uk", "zh-Hans"];
    public static void Register()
    {
        var dictionaries = Languages.ToDictionary(code => code, _ => new Dictionary<string, string>());
        foreach (var row in Rows.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var cells = row.Split('|');
            if (cells.Length != Languages.Length + 1) throw new InvalidOperationException($"Invalid translation row: {cells[0]}");
            for (int i = 0; i < Languages.Length; i++) dictionaries[Languages[i]]["main." + cells[0]] = cells[i + 1].Replace("\\n", "\n");
        }
        foreach (var (language, values) in dictionaries) L10n.RegisterTranslations(language, values);
    }

    private const string Rows = """
viewer|Image viewer|Просмотр изображений|Bildbetrachter|Visionneuse d’images|Visor de imágenes|Visualizzatore di immagini|Visualizador de imagens|Przeglądarka zdjęć|Перегляд зображень|图像查看器
dirty|Unsaved changes|Не сохранено|Nicht gespeichert|Non enregistré|Sin guardar|Non salvato|Não guardado|Niezapisane zmiany|Не збережено|尚未保存
open|Open images|Открыть изображения|Bilder öffnen|Ouvrir des images|Abrir imágenes|Apri immagini|Abrir imagens|Otwórz zdjęcia|Відкрити зображення|打开图像
openTip|Open images · Ctrl+O|Открыть изображения · Ctrl+O|Bilder öffnen · Ctrl+O|Ouvrir des images · Ctrl+O|Abrir imágenes · Ctrl+O|Apri immagini · Ctrl+O|Abrir imagens · Ctrl+O|Otwórz zdjęcia · Ctrl+O|Відкрити зображення · Ctrl+O|打开图像 · Ctrl+O
filmstrip|Filmstrip · T|Лента миниатюр · T|Filmstreifen · T|Pellicule · T|Tira de miniaturas · T|Striscia miniature · T|Faixa de miniaturas · T|Pasek miniatur · T|Стрічка мініатюр · T|缩略图栏 · T
info|Image information · I|Информация об изображении · I|Bildinformationen · I|Informations sur l’image · I|Información de imagen · I|Informazioni immagine · I|Informações da imagem · I|Informacje o zdjęciu · I|Інформація про зображення · I|图像信息 · I
settings|Settings|Настройки|Einstellungen|Paramètres|Configuración|Impostazioni|Definições|Ustawienia|Налаштування|设置
support|Support PhotoWoo|Поддержать PhotoWoo|PhotoWoo unterstützen|Soutenir PhotoWoo|Apoyar PhotoWoo|Sostieni PhotoWoo|Apoiar PhotoWoo|Wesprzyj PhotoWoo|Підтримати PhotoWoo|支持 PhotoWoo
emptyTitle|Open a photograph|Откройте фотографию|Ein Foto öffnen|Ouvrez une photo|Abre una fotografía|Apri una fotografia|Abra uma fotografia|Otwórz zdjęcie|Відкрийте фотографію|打开一张照片
emptyHint|Drop a file here or press Ctrl+O|Перетащите файл в окно или нажмите Ctrl+O|Datei hier ablegen oder Ctrl+O drücken|Déposez un fichier ici ou appuyez sur Ctrl+O|Arrastra un archivo aquí o pulsa Ctrl+O|Trascina un file qui o premi Ctrl+O|Arraste um ficheiro ou prima Ctrl+O|Przeciągnij plik tutaj lub naciśnij Ctrl+O|Перетягніть файл у вікно або натисніть Ctrl+O|将文件拖到此处，或按 Ctrl+O
formats|Images and RAW|Изображения и RAW|Bilder und RAW|Images et RAW|Imágenes y RAW|Immagini e RAW|Imagens e RAW|Zdjęcia i RAW|Зображення та RAW|图像和 RAW
allFiles|All files|Все файлы|Alle Dateien|Tous les fichiers|Todos los archivos|Tutti i file|Todos os ficheiros|Wszystkie pliki|Усі файли|所有文件
previous|Previous image · ←|Предыдущее изображение · ←|Vorheriges Bild · ←|Image précédente · ←|Imagen anterior · ←|Immagine precedente · ←|Imagem anterior · ←|Poprzednie zdjęcie · ←|Попереднє зображення · ←|上一张 · ←
next|Next image · →|Следующее изображение · →|Nächstes Bild · →|Image suivante · →|Imagen siguiente · →|Immagine successiva · →|Imagem seguinte · →|Następne zdjęcie · →|Наступне зображення · →|下一张 · →
opening|Opening…|Открытие…|Wird geöffnet…|Ouverture…|Abriendo…|Apertura…|A abrir…|Otwieranie…|Відкриття…|正在打开…
fullLoading|Preparing full resolution…|Подготовка полного разрешения…|Volle Auflösung wird geladen…|Préparation de la pleine résolution…|Preparando resolución completa…|Preparazione della piena risoluzione…|A preparar a resolução total…|Przygotowywanie pełnej rozdzielczości…|Підготовка повної роздільності…|正在准备完整分辨率…
zoomOut|Zoom out|Уменьшить|Verkleinern|Réduire|Alejar|Riduci|Reduzir|Pomniejsz|Зменшити|缩小
zoomIn|Zoom in|Увеличить|Vergrößern|Agrandir|Acercar|Ingrandisci|Ampliar|Powiększ|Збільшити|放大
fit|Fit to window · 0|Вписать в окно · 0|An Fenster anpassen · 0|Adapter à la fenêtre · 0|Ajustar a ventana · 0|Adatta alla finestra · 0|Ajustar à janela · 0|Dopasuj do okna · 0|Вписати у вікно · 0|适应窗口 · 0
rotateLeft|Rotate left 90° · Shift+R|Повернуть влево на 90° · Shift+R|90° nach links drehen · Shift+R|Tourner à gauche de 90° · Shift+R|Girar 90° a la izquierda · Shift+R|Ruota a sinistra di 90° · Shift+R|Rodar 90° à esquerda · Shift+R|Obróć w lewo o 90° · Shift+R|Повернути ліворуч на 90° · Shift+R|向左旋转 90° · Shift+R
rotateRight|Rotate right 90° · R|Повернуть вправо на 90° · R|90° nach rechts drehen · R|Tourner à droite de 90° · R|Girar 90° a la derecha · R|Ruota a destra di 90° · R|Rodar 90° à direita · R|Obróć w prawo o 90° · R|Повернути праворуч на 90° · R|向右旋转 90° · R
undo|Undo rotation · Ctrl+Z|Отменить поворот · Ctrl+Z|Drehung zurücksetzen · Ctrl+Z|Annuler la rotation · Ctrl+Z|Deshacer giro · Ctrl+Z|Annulla rotazione · Ctrl+Z|Anular rotação · Ctrl+Z|Cofnij obrót · Ctrl+Z|Скасувати поворот · Ctrl+Z|撤销旋转 · Ctrl+Z
save|Save|Сохранить|Speichern|Enregistrer|Guardar|Salva|Guardar|Zapisz|Зберегти|保存
saveTip|Save changes · Ctrl+S|Сохранить изменения · Ctrl+S|Änderungen speichern · Ctrl+S|Enregistrer les modifications · Ctrl+S|Guardar cambios · Ctrl+S|Salva modifiche · Ctrl+S|Guardar alterações · Ctrl+S|Zapisz zmiany · Ctrl+S|Зберегти зміни · Ctrl+S|保存更改 · Ctrl+S
copy|Save copy|Копия|Kopie|Copie|Copia|Copia|Cópia|Kopia|Копія|保存副本
copyTip|Save a copy · Ctrl+Shift+S|Сохранить копию · Ctrl+Shift+S|Kopie speichern · Ctrl+Shift+S|Enregistrer une copie · Ctrl+Shift+S|Guardar una copia · Ctrl+Shift+S|Salva una copia · Ctrl+Shift+S|Guardar uma cópia · Ctrl+Shift+S|Zapisz kopię · Ctrl+Shift+S|Зберегти копію · Ctrl+Shift+S|保存副本 · Ctrl+Shift+S
print|Print · Ctrl+P|Печать · Ctrl+P|Drucken · Ctrl+P|Imprimer · Ctrl+P|Imprimir · Ctrl+P|Stampa · Ctrl+P|Imprimir · Ctrl+P|Drukuj · Ctrl+P|Друк · Ctrl+P|打印 · Ctrl+P
fullscreen|Fullscreen · F11|Полный экран · F11|Vollbild · F11|Plein écran · F11|Pantalla completa · F11|Schermo intero · F11|Ecrã inteiro · F11|Pełny ekran · F11|На весь екран · F11|全屏 · F11
information|INFORMATION|ИНФОРМАЦИЯ|INFORMATIONEN|INFORMATIONS|INFORMACIÓN|INFORMAZIONI|INFORMAÇÕES|INFORMACJE|ІНФОРМАЦІЯ|信息
noImage|No image selected|Фото не выбрано|Kein Bild ausgewählt|Aucune image sélectionnée|Ninguna imagen seleccionada|Nessuna immagine selezionata|Nenhuma imagem selecionada|Nie wybrano zdjęcia|Фото не вибрано|未选择图像
noInfo|Open an image to see its information.|Откройте изображение, чтобы увидеть информацию.|Öffnen Sie ein Bild, um Informationen anzuzeigen.|Ouvrez une image pour afficher ses informations.|Abre una imagen para ver su información.|Apri un’immagine per visualizzarne le informazioni.|Abra uma imagem para ver as suas informações.|Otwórz zdjęcie, aby zobaczyć informacje.|Відкрийте зображення, щоб побачити інформацію.|打开图像以查看信息。
rawHint|RAW may first show an embedded preview. Full resolution is prepared separately.|Для RAW сначала может отображаться встроенное превью. Полное разрешение подготавливается отдельно.|Bei RAW wird zunächst eventuell die eingebettete Vorschau angezeigt. Die volle Auflösung wird separat geladen.|Le RAW peut d’abord afficher un aperçu intégré. La pleine résolution est préparée séparément.|RAW puede mostrar primero una vista previa integrada. La resolución completa se prepara por separado.|Il RAW può mostrare prima un’anteprima incorporata. La piena risoluzione viene preparata separatamente.|RAW pode mostrar primeiro uma pré-visualização incorporada. A resolução total é preparada separadamente.|RAW może najpierw wyświetlić wbudowany podgląd. Pełna rozdzielczość jest przygotowywana osobno.|Для RAW спочатку може відображатися вбудоване прев’ю. Повна роздільність готується окремо.|RAW 可能先显示内嵌预览，完整分辨率将单独处理。
fullQuality|Full resolution|Полное разрешение|Volle Auflösung|Pleine résolution|Resolución completa|Piena risoluzione|Resolução total|Pełna rozdzielczość|Повна роздільність|完整分辨率
folderImages|Images in folder|Изображения в папке|Bilder im Ordner|Images du dossier|Imágenes de la carpeta|Immagini nella cartella|Imagens na pasta|Zdjęcia w folderze|Зображення в папці|文件夹中的图像
ready|Ready|Готово|Bereit|Prêt|Listo|Pronto|Pronto|Gotowe|Готово|就绪
preview|Preview|Превью|Vorschau|Aperçu|Vista previa|Anteprima|Pré-visualização|Podgląd|Прев’ю|预览
image|Image|Изображение|Bild|Image|Imagen|Immagine|Imagem|Zdjęcie|Зображення|图像
timing|{0} · {1:N0} ms|{0} · {1:N0} мс|{0} · {1:N0} ms|{0} · {1:N0} ms|{0} · {1:N0} ms|{0} · {1:N0} ms|{0} · {1:N0} ms|{0} · {1:N0} ms|{0} · {1:N0} мс|{0} · {1:N0} 毫秒
fileSize|{0:N1} MB|{0:N1} МБ|{0:N1} MB|{0:N1} Mo|{0:N1} MB|{0:N1} MB|{0:N1} MB|{0:N1} MB|{0:N1} МБ|{0:N1} MB
sourceMissing|Source file unavailable|Исходный файл недоступен|Quelldatei nicht verfügbar|Fichier source indisponible|Archivo original no disponible|File originale non disponibile|Ficheiro original indisponível|Plik źródłowy niedostępny|Вихідний файл недоступний|源文件不可用
rawPreview|Embedded RAW preview. Full resolution is available for details.|Встроенное превью RAW. Для деталей доступно полное разрешение.|Eingebettete RAW-Vorschau. Volle Auflösung für Details verfügbar.|Aperçu RAW intégré. Pleine résolution disponible pour les détails.|Vista previa RAW integrada. Resolución completa disponible para los detalles.|Anteprima RAW incorporata. Piena risoluzione disponibile per i dettagli.|Pré-visualização RAW incorporada. Resolução total disponível para detalhes.|Wbudowany podgląd RAW. Pełna rozdzielczość jest dostępna do oglądania szczegółów.|Вбудоване прев’ю RAW. Для деталей доступна повна роздільність.|RAW 内嵌预览。可加载完整分辨率查看细节。
fastPreview|Quick-view copy. Full resolution is available.|Копия для быстрого просмотра. Доступно полное разрешение.|Kopie für die schnelle Vorschau. Volle Auflösung verfügbar.|Copie pour aperçu rapide. Pleine résolution disponible.|Copia de vista rápida. Resolución completa disponible.|Copia per anteprima rapida. Piena risoluzione disponibile.|Cópia para visualização rápida. Resolução total disponível.|Kopia do szybkiego podglądu. Pełna rozdzielczość jest dostępna.|Копія для швидкого перегляду. Доступна повна роздільність.|快速查看副本。可加载完整分辨率。
infoDetails|{0}\n\n{1:N0} × {2:N0} pixels\n{3}\n\nRotation: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} пикселей\n{3}\n\nПоворот: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} Pixel\n{3}\n\nDrehung: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} pixels\n{3}\n\nRotation : {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} píxeles\n{3}\n\nGiro: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} pixel\n{3}\n\nRotazione: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} píxeis\n{3}\n\nRotação: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} pikseli\n{3}\n\nObrót: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} пікселів\n{3}\n\nПоворот: {4}°\n\n{5}|{0}\n\n{1:N0} × {2:N0} 像素\n{3}\n\n旋转：{4}°\n\n{5}
unsupported|This format is not supported yet. Choose another file.|Этот формат пока не поддерживается. Выберите другой файл.|Dieses Format wird noch nicht unterstützt. Wählen Sie eine andere Datei.|Ce format n’est pas encore pris en charge. Choisissez un autre fichier.|Este formato aún no es compatible. Elige otro archivo.|Questo formato non è ancora supportato. Scegli un altro file.|Este formato ainda não é suportado. Escolha outro ficheiro.|Ten format nie jest jeszcze obsługiwany. Wybierz inny plik.|Цей формат поки не підтримується. Виберіть інший файл.|暂不支持此格式，请选择其他文件。
folderUnavailable|Image opened. Folder unavailable: {0}|Фото открыто. Папка недоступна: {0}|Bild geöffnet. Ordner nicht verfügbar: {0}|Image ouverte. Dossier indisponible : {0}|Imagen abierta. Carpeta no disponible: {0}|Immagine aperta. Cartella non disponibile: {0}|Imagem aberta. Pasta indisponível: {0}|Zdjęcie otwarte. Folder niedostępny: {0}|Фото відкрито. Папка недоступна: {0}|图像已打开，文件夹不可用：{0}
openFailed|Unable to open image|Не удалось открыть изображение|Bild konnte nicht geöffnet werden|Impossible d’ouvrir l’image|No se pudo abrir la imagen|Impossibile aprire l’immagine|Não foi possível abrir a imagem|Nie można otworzyć zdjęcia|Не вдалося відкрити зображення|无法打开图像
rawExport|Export RAW — the original will stay unchanged|Экспорт RAW — исходник останется без изменений|RAW exportieren — Original bleibt unverändert|Exporter le RAW — l’original reste inchangé|Exportar RAW — el original no cambiará|Esporta RAW — l’originale rimarrà invariato|Exportar RAW — o original não será alterado|Eksport RAW — oryginał pozostanie bez zmian|Експорт RAW — оригінал залишиться без змін|导出 RAW — 保留原始文件
saveCopyTitle|Save a rotated copy|Сохранить повёрнутую копию|Gedrehte Kopie speichern|Enregistrer une copie tournée|Guardar una copia girada|Salva una copia ruotata|Guardar uma cópia rodada|Zapisz obróconą kopię|Зберегти повернуту копію|保存旋转后的副本
copyName|_rotated|_повёрнуто|_gedreht|_rotation|_girada|_ruotata|_rodada|_obrocone|_повернуто|_已旋转
differentName|Choose a different name for the copy. The original will stay unchanged.|Для копии выберите другое имя. Исходный файл останется без изменений.|Wählen Sie für die Kopie einen anderen Namen. Das Original bleibt unverändert.|Choisissez un autre nom pour la copie. L’original reste inchangé.|Elige otro nombre para la copia. El original no cambiará.|Scegli un altro nome per la copia. L’originale rimarrà invariato.|Escolha outro nome para a cópia. O original não será alterado.|Wybierz inną nazwę kopii. Oryginał pozostanie bez zmian.|Виберіть інше ім’я для копії. Оригінал залишиться без змін.|请为副本选择其他名称，原始文件将保持不变。
saving|Saving full-resolution image…|Сохранение полного изображения…|Bild in voller Auflösung wird gespeichert…|Enregistrement en pleine résolution…|Guardando imagen a resolución completa…|Salvataggio dell’immagine a piena risoluzione…|A guardar a imagem em resolução total…|Zapisywanie zdjęcia w pełnej rozdzielczości…|Збереження повного зображення…|正在保存完整分辨率图像…
saved|Saved: {0}|Сохранено: {0}|Gespeichert: {0}|Enregistré : {0}|Guardado: {0}|Salvato: {0}|Guardado: {0}|Zapisano: {0}|Збережено: {0}|已保存：{0}
saveFailed|Unable to save. The original was not replaced.\n\n{0}|Не удалось сохранить. Исходник не заменён.\n\n{0}|Speichern fehlgeschlagen. Das Original wurde nicht ersetzt.\n\n{0}|Échec de l’enregistrement. L’original n’a pas été remplacé.\n\n{0}|No se pudo guardar. El original no se ha sustituido.\n\n{0}|Salvataggio non riuscito. L’originale non è stato sostituito.\n\n{0}|Não foi possível guardar. O original não foi substituído.\n\n{0}|Nie można zapisać. Oryginał nie został zastąpiony.\n\n{0}|Не вдалося зберегти. Оригінал не замінено.\n\n{0}|无法保存，原始文件未被替换。\n\n{0}
unsavedTitle|Unsaved changes|Есть несохранённые изменения|Nicht gespeicherte Änderungen|Modifications non enregistrées|Cambios sin guardar|Modifiche non salvate|Alterações não guardadas|Niezapisane zmiany|Є незбережені зміни|尚未保存的更改
saveQuestion|Save the rotation of this photo?\n\nYes — save, No — discard, Cancel — keep viewing.|Сохранить поворот текущей фотографии?\n\nДа — сохранить, Нет — не сохранять, Отмена — продолжить просмотр.|Drehung dieses Fotos speichern?\n\nJa — speichern, Nein — verwerfen, Abbrechen — weiter ansehen.|Enregistrer la rotation de cette photo ?\n\nOui — enregistrer, Non — ignorer, Annuler — continuer.|¿Guardar el giro de esta foto?\n\nSí — guardar, No — descartar, Cancelar — seguir viendo.|Salvare la rotazione di questa foto?\n\nSì — salva, No — scarta, Annulla — continua a visualizzare.|Guardar a rotação desta foto?\n\nSim — guardar, Não — descartar, Cancelar — continuar.|Zapisać obrót tego zdjęcia?\n\nTak — zapisz, Nie — odrzuć, Anuluj — przeglądaj dalej.|Зберегти поворот поточної фотографії?\n\nТак — зберегти, Ні — не зберігати, Скасувати — продовжити перегляд.|保存此照片的旋转吗？\n\n是 — 保存，否 — 放弃，取消 — 继续查看。
preparingPrint|Preparing image for printing…|Подготовка изображения к печати…|Bild zum Drucken wird vorbereitet…|Préparation de l’image pour l’impression…|Preparando imagen para imprimir…|Preparazione dell’immagine per la stampa…|A preparar a imagem para impressão…|Przygotowywanie zdjęcia do druku…|Підготовка зображення до друку…|正在准备打印图像…
printFailed|Unable to prepare printing.\n\n{0}|Не удалось подготовить печать.\n\n{0}|Druck konnte nicht vorbereitet werden.\n\n{0}|Impossible de préparer l’impression.\n\n{0}|No se pudo preparar la impresión.\n\n{0}|Impossibile preparare la stampa.\n\n{0}|Não foi possível preparar a impressão.\n\n{0}|Nie można przygotować wydruku.\n\n{0}|Не вдалося підготувати друк.\n\n{0}|无法准备打印。\n\n{0}
supportMissing|The creator’s support page has not been set yet. Add its address in Settings → About.|Страница поддержки автора пока не указана. Добавьте адрес в Настройки → О программе.|Die Unterstützungsseite ist noch nicht eingerichtet. Adresse unter Einstellungen → Über hinzufügen.|La page de soutien n’est pas encore définie. Ajoutez son adresse dans Paramètres → À propos.|La página de apoyo aún no está configurada. Añádela en Configuración → Acerca de.|La pagina di supporto non è ancora impostata. Aggiungi l’indirizzo in Impostazioni → Informazioni.|A página de apoio ainda não está definida. Adicione o endereço em Definições → Sobre.|Strona wsparcia nie jest jeszcze ustawiona. Dodaj adres w Ustawienia → O programie.|Сторінку підтримки автора ще не вказано. Додайте адресу в Налаштування → Про програму.|尚未设置作者的支持页面。请在“设置 → 关于”中添加地址。
linkFailed|Unable to open the link: {0}|Не удалось открыть ссылку: {0}|Link konnte nicht geöffnet werden: {0}|Impossible d’ouvrir le lien : {0}|No se pudo abrir el enlace: {0}|Impossibile aprire il collegamento: {0}|Não foi possível abrir a ligação: {0}|Nie można otworzyć odnośnika: {0}|Не вдалося відкрити посилання: {0}|无法打开链接：{0}
help|Controls · F1|Управление · F1|Bedienung · F1|Commandes · F1|Controles · F1|Comandi · F1|Controlos · F1|Sterowanie · F1|Керування · F1|操作说明 · F1
""";
}
