namespace PhotoWoo.Localization;

public static class ModelTranslations
{
    private static readonly string[] Languages = ["en", "ru", "de", "fr", "es", "it", "pt", "pl", "uk", "zh-Hans"];
    public static void Register()
    {
        var dictionaries = Languages.ToDictionary(code => code, _ => new Dictionary<string, string>());
        foreach (var row in Rows.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var cells = row.Split('|');
            if (cells.Length != Languages.Length + 1) throw new InvalidOperationException($"Invalid translation row: {cells[0]}");
            for (var i = 0; i < Languages.Length; i++) dictionaries[Languages[i]][cells[0]] = cells[i + 1].Replace("\\n", "\n");
        }
        foreach (var (language, values) in dictionaries) L10n.RegisterTranslations(language, values);
    }

    private const string Rows = """
main.open|Open file|Открыть файл|Datei öffnen|Ouvrir un fichier|Abrir archivo|Apri file|Abrir ficheiro|Otwórz plik|Відкрити файл|打开文件
main.emptyTitle|Open an image or 3D model|Откройте изображение или 3D-модель|Bild oder 3D-Modell öffnen|Ouvrez une image ou un modèle 3D|Abre una imagen o un modelo 3D|Apri un’immagine o un modello 3D|Abra uma imagem ou um modelo 3D|Otwórz obraz lub model 3D|Відкрийте зображення або 3D-модель|打开图像或 3D 模型
models.allFormats|Images, RAW and 3D models|Изображения, RAW и 3D-модели|Bilder, RAW und 3D-Modelle|Images, RAW et modèles 3D|Imágenes, RAW y modelos 3D|Immagini, RAW e modelli 3D|Imagens, RAW e modelos 3D|Obrazy, RAW i modele 3D|Зображення, RAW і 3D-моделі|图像、RAW 和 3D 模型
models.formats|3D models (GLB, glTF)|3D-модели (GLB, glTF)|3D-Modelle (GLB, glTF)|Modèles 3D (GLB, glTF)|Modelos 3D (GLB, glTF)|Modelli 3D (GLB, glTF)|Modelos 3D (GLB, glTF)|Modele 3D (GLB, glTF)|3D-моделі (GLB, glTF)|3D 模型 (GLB、glTF)
models.controls|Drag to orbit · Right-drag to pan · Wheel to zoom · Double-click to reset|Тяните — вращение · ПКМ — перемещение · Колесо — масштаб · Двойной щелчок — сброс|Ziehen: drehen · Rechts ziehen: verschieben · Mausrad: Zoom · Doppelklick: zurücksetzen|Glisser : tourner · Glisser à droite : déplacer · Molette : zoom · Double-clic : réinitialiser|Arrastrar: girar · Botón derecho: desplazar · Rueda: zoom · Doble clic: restablecer|Trascina: ruota · Tasto destro: sposta · Rotella: zoom · Doppio clic: ripristina|Arrastar: rodar · Botão direito: mover · Roda: zoom · Duplo clique: repor|Przeciągnij: obrót · Prawy przycisk: przesuń · Kółko: zoom · Dwuklik: reset|Перетягування — обертання · ПКМ — переміщення · Колесо — масштаб · Подвійний клік — скидання|拖动旋转 · 右键拖动平移 · 滚轮缩放 · 双击重置
models.hint|Basic 3D view with textures and diffuse lighting. Models are shown in their default pose; animation playback and full PBR materials are not supported.\n\nDrag to orbit. Right-drag, middle-drag or Shift-drag to pan. Wheel to zoom; 0 or double-click to reset.|Базовый 3D-просмотр с текстурами и простым освещением. Модель показана в исходной позе; воспроизведение анимаций и полноценные PBR-материалы не поддерживаются.\n\nПеретягивание — вращение. ПКМ, средняя кнопка или Shift — перемещение. Колесо — масштаб; 0 или двойной щелчок — сброс.|Einfache 3D-Ansicht mit Texturen und diffusem Licht. Standardpose, ohne Animationswiedergabe oder vollständige PBR-Materialien.\n\nZiehen: drehen. Rechts, mittig oder mit Shift ziehen: verschieben. Mausrad: Zoom; 0 oder Doppelklick: zurücksetzen.|Vue 3D simple avec textures et éclairage diffus. Pose par défaut, sans lecture d’animation ni matériaux PBR complets.\n\nGlisser : tourner. Bouton droit, central ou Maj : déplacer. Molette : zoom ; 0 ou double-clic : réinitialiser.|Vista 3D básica con texturas e iluminación difusa. Pose inicial, sin reproducción de animaciones ni materiales PBR completos.\n\nArrastrar: girar. Botón derecho, central o Mayús: desplazar. Rueda: zoom; 0 o doble clic: restablecer.|Vista 3D di base con texture e luce diffusa. Posa iniziale, senza animazioni o materiali PBR completi.\n\nTrascina: ruota. Tasto destro, centrale o Maiusc: sposta. Rotella: zoom; 0 o doppio clic: ripristina.|Vista 3D básica com texturas e luz difusa. Pose inicial, sem reprodução de animações nem materiais PBR completos.\n\nArrastar: rodar. Botão direito, central ou Shift: mover. Roda: zoom; 0 ou duplo clique: repor.|Podstawowy widok 3D z teksturami i światłem rozproszonym. Poza domyślna, bez odtwarzania animacji i pełnych materiałów PBR.\n\nPrzeciągnij: obrót. Prawy, środkowy przycisk lub Shift: przesuń. Kółko: zoom; 0 lub dwuklik: reset.|Базовий 3D-перегляд із текстурами та простим освітленням. Початкова поза, без відтворення анімацій і повних PBR-матеріалів.\n\nПеретягування — обертання. ПКМ, середня кнопка або Shift — переміщення. Колесо — масштаб; 0 або подвійний клік — скидання.|基础 3D 查看，支持纹理和漫反射光照。显示默认姿势，不支持动画播放或完整 PBR 材质。\n\n拖动旋转。右键、中键或 Shift 拖动平移。滚轮缩放；0 或双击重置。
models.details|{0} · {1:N0} triangles|{0} · {1:N0} треугольников|{0} · {1:N0} Dreiecke|{0} · {1:N0} triangles|{0} · {1:N0} triángulos|{0} · {1:N0} triangoli|{0} · {1:N0} triângulos|{0} · {1:N0} trójkątów|{0} · {1:N0} трикутників|{0} · {1:N0} 个三角形
models.info|{0}\nMeshes: {1:N0}\nTriangles: {2:N0}\nAnimation tracks: {3:N0}|{0}\nМешей: {1:N0}\nТреугольников: {2:N0}\nТреков анимации: {3:N0}|{0}\nMeshes: {1:N0}\nDreiecke: {2:N0}\nAnimationsspuren: {3:N0}|{0}\nMaillages : {1:N0}\nTriangles : {2:N0}\nAnimations : {3:N0}|{0}\nMallas: {1:N0}\nTriángulos: {2:N0}\nAnimaciones: {3:N0}|{0}\nMesh: {1:N0}\nTriangoli: {2:N0}\nAnimazioni: {3:N0}|{0}\nMalhas: {1:N0}\nTriângulos: {2:N0}\nAnimações: {3:N0}|{0}\nSiatki: {1:N0}\nTrójkąty: {2:N0}\nAnimacje: {3:N0}|{0}\nМешів: {1:N0}\nТрикутників: {2:N0}\nТреків анімації: {3:N0}|{0}\n网格：{1:N0}\n三角形：{2:N0}\n动画轨道：{3:N0}
models.assigned|Default for {0} of {1} supported extensions|Назначено для {0} из {1} поддерживаемых расширений|Standard für {0} von {1} unterstützten Endungen|Par défaut pour {0} extensions sur {1}|Predeterminado para {0} de {1} extensiones|Predefinito per {0} estensioni su {1}|Predefinido para {0} de {1} extensões|Domyślna dla {0} z {1} rozszerzeń|Призначено для {0} із {1} підтримуваних розширень|已设为 {0}/{1} 种受支持扩展名的默认应用
models.registered|All {0} extensions are registered. Complete the default-app selection in Windows.|Все расширения ({0}) зарегистрированы. Завершите выбор приложения по умолчанию в Windows.|Alle {0} Endungen sind registriert. Schließen Sie die Auswahl in Windows ab.|Les {0} extensions sont enregistrées. Terminez le choix dans Windows.|Las {0} extensiones están registradas. Completa la selección en Windows.|Tutte le {0} estensioni sono registrate. Completa la scelta in Windows.|As {0} extensões estão registadas. Conclua a escolha no Windows.|Zarejestrowano {0} rozszerzeń. Dokończ wybór w systemie Windows.|Усі розширення ({0}) зареєстровано. Завершіть вибір у Windows.|已注册全部 {0} 种扩展名。请在 Windows 中完成默认应用选择。
""";
}
