namespace PhotoWoo.Localization;

internal static class SettingsTranslations
{
    internal static Dictionary<string, Dictionary<string, string>> Create()
    {
        string[] languages = ["en", "ru", "de", "fr", "es", "it", "pt", "pl", "uk", "zh-Hans"];
        var result = languages.ToDictionary(language => language, _ => new Dictionary<string, string>(StringComparer.Ordinal), StringComparer.Ordinal);
        foreach (var row in Table.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var fields = row.Split('|');
            if (fields.Length != languages.Length + 1) throw new InvalidOperationException("Incomplete translation: " + fields[0]);
            for (var i = 0; i < languages.Length; i++) result[languages[i]].Add(fields[0], fields[i + 1].Replace("\\n", "\n"));
        }
        return result;
    }

    private const string Table = """
settings.title|Settings — PhotoWoo|Настройки — PhotoWoo|Einstellungen — PhotoWoo|Paramètres — PhotoWoo|Ajustes — PhotoWoo|Impostazioni — PhotoWoo|Definições — PhotoWoo|Ustawienia — PhotoWoo|Налаштування — PhotoWoo|设置 — PhotoWoo
settings.subtitle|Make the viewer feel right for you.|Настройте просмотрщик под себя.|Passen Sie den Bildbetrachter an Ihre Arbeitsweise an.|Adaptez la visionneuse à votre façon de travailler.|Adapta el visor a tu forma de trabajar.|Adatta il visualizzatore al tuo modo di lavorare.|Adapte o visualizador à sua forma de trabalhar.|Dostosuj przeglądarkę do swoich potrzeb.|Налаштуйте переглядач під себе.|按您的习惯调整查看器。
settings.tab.viewing|Viewing|Просмотр|Ansicht|Affichage|Vista|Visualizzazione|Visualização|Wyświetlanie|Перегляд|查看
settings.tab.controls|Controls|Управление|Bedienung|Commandes|Controles|Comandi|Controlos|Sterowanie|Керування|操作
settings.tab.windows|Windows|Windows|Windows|Windows|Windows|Windows|Windows|Windows|Windows|Windows
settings.tab.about|About & support|О программе|Info & Unterstützung|À propos et soutien|Acerca de y apoyo|Informazioni e supporto|Sobre e apoio|O programie i wsparcie|Про програму|关于与支持
settings.language|Interface language|Язык интерфейса|Sprache der Oberfläche|Langue de l’interface|Idioma de la interfaz|Lingua dell’interfaccia|Idioma da interface|Język interfejsu|Мова інтерфейсу|界面语言
settings.language.auto|Use Windows language|Как в Windows|Windows-Sprache verwenden|Utiliser la langue de Windows|Usar el idioma de Windows|Usa la lingua di Windows|Usar o idioma do Windows|Użyj języka systemu Windows|Як у Windows|使用 Windows 语言
settings.language.hint|The interface changes immediately. Cancel restores the previous language.|Язык меняется сразу. «Отмена» вернёт прежний язык.|Die Sprache ändert sich sofort. Abbrechen stellt die vorherige Sprache wieder her.|La langue change immédiatement. Annuler rétablit la langue précédente.|El idioma cambia al instante. Cancelar restaura el idioma anterior.|La lingua cambia subito. Annulla ripristina quella precedente.|O idioma muda imediatamente. Cancelar repõe o idioma anterior.|Język zmienia się od razu. Anuluj przywraca poprzedni język.|Мова змінюється одразу. «Скасувати» поверне попередню мову.|语言会立即切换。取消将恢复之前的语言。
settings.motion|Interface & movement|Интерфейс и движение|Oberfläche und Bewegung|Interface et mouvements|Interfaz y movimiento|Interfaccia e movimento|Interface e movimento|Interfejs i ruch|Інтерфейс і рух|界面与动效
settings.animations|Smooth animations|Плавные анимации|Sanfte Animationen|Animations fluides|Animaciones suaves|Animazioni fluide|Animações suaves|Płynne animacje|Плавні анімації|平滑动画
settings.animations.hint|Short transitions for zoom, rotation, panels and buttons. Respects Windows motion settings.|Короткие переходы масштаба, поворота, панелей и кнопок. Учитываются настройки анимации Windows.|Kurze Übergänge beim Zoomen, Drehen und Bedienen. Berücksichtigt die Windows-Animationseinstellungen.|Transitions brèves du zoom, de la rotation et des commandes. Respecte les réglages d’animation de Windows.|Transiciones breves de zoom, giro y controles. Respeta los ajustes de animación de Windows.|Transizioni brevi per zoom, rotazione e comandi. Rispetta le impostazioni di animazione di Windows.|Transições breves de zoom, rotação e controlos. Respeita as definições de animação do Windows.|Krótkie przejścia powiększania, obrotu i elementów interfejsu. Uwzględnia ustawienia animacji Windows.|Короткі переходи масштабу, повороту, панелей і кнопок. Враховує налаштування анімації Windows.|为缩放、旋转、面板和按钮添加短暂过渡，并遵循 Windows 动画设置。
settings.inertia|Inertia after dragging|Инерция после перетаскивания|Trägheit nach dem Ziehen|Inertie après un glissement|Inercia tras arrastrar|Inerzia dopo il trascinamento|Inércia após arrastar|Bezwładność po przeciągnięciu|Інерція після перетягування|拖动后的惯性
settings.inertia.hint|The image and thumbnail strip glide gently after release.|Изображение и лента мягко продолжают движение после отпускания.|Bild und Filmstreifen gleiten nach dem Loslassen sanft weiter.|L’image et la bande de vignettes continuent à glisser après le relâchement.|La imagen y la tira de miniaturas siguen deslizándose al soltar.|L’immagine e la striscia di miniature continuano a scorrere al rilascio.|A imagem e a faixa de miniaturas continuam a deslizar após soltar.|Obraz i pasek miniatur łagodnie przesuwają się po zwolnieniu.|Зображення та стрічка плавно продовжують рух після відпускання.|松开后，图像和缩略图条会平缓滑动。
settings.filmstrip|Show thumbnail strip|Показывать ленту миниатюр|Filmstreifen anzeigen|Afficher les vignettes|Mostrar la tira de miniaturas|Mostra la striscia di miniature|Mostrar a faixa de miniaturas|Pokaż pasek miniatur|Показувати стрічку мініатюр|显示缩略图条
settings.filmstrip.hint|You can also toggle it at any time with T.|Её также можно включать и скрывать клавишей T.|Auch jederzeit mit T ein- und ausblendbar.|Vous pouvez aussi l’afficher ou la masquer avec T.|También puedes mostrarla u ocultarla con T.|Puoi mostrarla o nasconderla anche con T.|Também pode mostrar ou ocultar com T.|Możesz ją też włączać i wyłączać klawiszem T.|Її також можна вмикати та приховувати клавішею T.|也可随时按 T 显示或隐藏。
settings.fullscreen|Fullscreen|Полный экран|Vollbild|Plein écran|Pantalla completa|Schermo intero|Ecrã inteiro|Pełny ekran|Повний екран|全屏
settings.fill|Fill the screen|Заполнять экран|Bildschirm ausfüllen|Remplir l’écran|Llenar la pantalla|Riempi lo schermo|Preencher o ecrã|Wypełnij ekran|Заповнювати екран|填满屏幕
settings.fill.hint|Crop the edges to fill the screen. Off keeps the entire image visible.|Края обрезаются по размеру экрана. Выключено — снимок виден целиком.|Die Ränder werden beschnitten. Ausgeschaltet bleibt das ganze Bild sichtbar.|Les bords sont rognés. Désactivé, l’image reste entièrement visible.|Se recortan los bordes. Desactivado, se muestra toda la imagen.|I bordi vengono ritagliati. Se disattivato, l’immagine resta interamente visibile.|As margens são recortadas. Desativado, mostra a imagem inteira.|Krawędzie są przycinane. Po wyłączeniu cały obraz jest widoczny.|Краї обрізаються під розмір екрана. Вимкнено — знімок видно повністю.|裁切边缘以铺满屏幕。关闭时显示完整图像。
settings.hideDelay|Hide controls after inactivity|Скрывать панели без движения мыши|Bedienelemente bei Inaktivität ausblenden|Masquer les commandes après inactivité|Ocultar controles tras inactividad|Nascondi i comandi dopo inattività|Ocultar controlos após inatividade|Ukryj elementy sterowania po bezczynności|Приховувати панелі без руху миші|无操作后隐藏控件
settings.delayFormat|{0} seconds|{0} сек.|{0} Sekunden|{0} secondes|{0} segundos|{0} secondi|{0} segundos|{0} s|{0} с|{0} 秒
settings.save|Save settings|Сохранить настройки|Einstellungen speichern|Enregistrer|Guardar ajustes|Salva impostazioni|Guardar definições|Zapisz ustawienia|Зберегти налаштування|保存设置
settings.cancel|Cancel|Отмена|Abbrechen|Annuler|Cancelar|Annulla|Cancelar|Anuluj|Скасувати|取消
settings.windows.title|PhotoWoo in Windows|PhotoWoo в Windows|PhotoWoo in Windows|PhotoWoo dans Windows|PhotoWoo en Windows|PhotoWoo in Windows|PhotoWoo no Windows|PhotoWoo w Windows|PhotoWoo у Windows|在 Windows 中使用 PhotoWoo
settings.windows.intro|Open images from File Explorer with a double-click.|Открывайте изображения двойным щелчком из Проводника.|Öffnen Sie Bilder per Doppelklick im Datei-Explorer.|Ouvrez les images par un double-clic dans l’Explorateur.|Abre imágenes con un doble clic desde el Explorador de archivos.|Apri le immagini con un doppio clic da Esplora file.|Abra imagens com um duplo clique no Explorador de Ficheiros.|Otwieraj obrazy dwukrotnym kliknięciem w Eksploratorze.|Відкривайте зображення подвійним клацанням у Провіднику.|在文件资源管理器中双击打开图像。
settings.icon.title|A distinctive image-file icon|Свой значок для изображений|Eigenes Symbol für Bilddateien|Une icône dédiée aux images|Un icono propio para imágenes|Un’icona dedicata alle immagini|Um ícone próprio para imagens|Własna ikona plików graficznych|Власна піктограма зображень|专属的图像文件图标
settings.icon.hint|Appears for associated files wherever Windows shows icons instead of thumbnails.|Появится у связанных файлов там, где Windows показывает значки вместо миниатюр.|Erscheint bei zugeordneten Dateien, wenn Windows Symbole statt Vorschaubilder anzeigt.|S’affiche pour les fichiers associés lorsque Windows montre des icônes plutôt que des vignettes.|Aparece en archivos asociados cuando Windows muestra iconos en lugar de miniaturas.|Compare per i file associati quando Windows mostra icone anziché miniature.|Surge nos ficheiros associados quando o Windows apresenta ícones em vez de miniaturas.|Jest widoczna przy skojarzonych plikach, gdy Windows pokazuje ikony zamiast miniatur.|З’явиться для пов’язаних файлів там, де Windows показує піктограми замість мініатюр.|Windows 使用图标而非缩略图时，会显示在关联的文件上。
settings.windows.permanent|Keep the PhotoWoo folder in a permanent location. Then choose PhotoWoo and the file types in Windows Settings.|Оставьте папку PhotoWoo в постоянном месте. Затем выберите PhotoWoo и нужные форматы в параметрах Windows.|Belassen Sie den PhotoWoo-Ordner an einem festen Ort. Wählen Sie danach PhotoWoo und die Dateitypen in den Windows-Einstellungen.|Conservez le dossier PhotoWoo à un emplacement fixe, puis choisissez PhotoWoo et les formats dans les paramètres Windows.|Guarda la carpeta PhotoWoo en una ubicación permanente. Después, elige PhotoWoo y los formatos en Configuración de Windows.|Mantieni la cartella PhotoWoo in una posizione fissa. Poi scegli PhotoWoo e i formati nelle impostazioni di Windows.|Mantenha a pasta PhotoWoo num local permanente. Depois escolha PhotoWoo e os formatos nas Definições do Windows.|Pozostaw folder PhotoWoo w stałym miejscu. Następnie wybierz PhotoWoo i formaty w ustawieniach Windows.|Залиште папку PhotoWoo в постійному місці. Потім виберіть PhotoWoo та потрібні формати в параметрах Windows.|请将 PhotoWoo 文件夹保存在固定位置，然后在 Windows 设置中选择 PhotoWoo 及其文件类型。
settings.windows.chooseDefault|Choose as default app|Выбрать приложением по умолчанию|Als Standard-App auswählen|Choisir comme application par défaut|Elegir como aplicación predeterminada|Scegli come app predefinita|Escolher como aplicação predefinida|Wybierz jako aplikację domyślną|Вибрати типовою програмою|选择为默认应用
settings.windows.note|Windows will ask you to confirm your choice.|Выбор подтверждается в параметрах Windows.|Bestätigen Sie Ihre Auswahl in den Windows-Einstellungen.|Le choix se confirme dans les paramètres Windows.|La elección se confirma en Configuración de Windows.|La scelta si conferma nelle impostazioni di Windows.|A escolha é confirmada nas Definições do Windows.|Wybór potwierdzisz w ustawieniach Windows.|Вибір підтверджується в параметрах Windows.|请在 Windows 设置中确认选择。
settings.windows.done|PhotoWoo is registered. Choose it for the formats you want in Windows Settings.|PhotoWoo зарегистрирован. Выберите его для нужных форматов в параметрах Windows.|PhotoWoo ist registriert. Wählen Sie es für die gewünschten Formate in den Windows-Einstellungen.|PhotoWoo est enregistré. Choisissez-le pour les formats souhaités dans les paramètres Windows.|PhotoWoo está registrado. Elígelo para los formatos deseados en Configuración de Windows.|PhotoWoo è registrato. Sceglilo per i formati desiderati nelle impostazioni di Windows.|O PhotoWoo está registado. Escolha-o para os formatos pretendidos nas Definições do Windows.|PhotoWoo jest zarejestrowany. Wybierz go dla odpowiednich formatów w ustawieniach Windows.|PhotoWoo зареєстровано. Виберіть його для потрібних форматів у параметрах Windows.|PhotoWoo 已注册。请在 Windows 设置中为所需格式选择它。
settings.windows.error|Could not open default-app settings: {0}|Не удалось открыть параметры приложений: {0}|Standard-App-Einstellungen konnten nicht geöffnet werden: {0}|Impossible d’ouvrir les paramètres des applications : {0}|No se pudieron abrir los ajustes de aplicaciones: {0}|Impossibile aprire le impostazioni delle app: {0}|Não foi possível abrir as definições de aplicações: {0}|Nie można otworzyć ustawień aplikacji: {0}|Не вдалося відкрити параметри програм: {0}|无法打开默认应用设置：{0}
settings.windows.exeError|Could not locate PhotoWoo.exe.|Не удалось определить путь к PhotoWoo.exe.|PhotoWoo.exe wurde nicht gefunden.|Impossible de trouver PhotoWoo.exe.|No se encontró PhotoWoo.exe.|Impossibile trovare PhotoWoo.exe.|Não foi possível encontrar PhotoWoo.exe.|Nie znaleziono PhotoWoo.exe.|Не вдалося знайти PhotoWoo.exe.|找不到 PhotoWoo.exe。
settings.about.title|A quiet space for your photographs.|Спокойное пространство для ваших фотографий.|Ein ruhiger Raum für Ihre Fotografien.|Un espace calme pour vos photographies.|Un espacio tranquilo para tus fotografías.|Uno spazio tranquillo per le tue fotografie.|Um espaço tranquilo para as suas fotografias.|Spokojna przestrzeń dla Twoich zdjęć.|Спокійний простір для ваших фотографій.|安静、专注的照片空间。
settings.about.description|A fast Windows image viewer for everyday images and camera RAW files, with rotation, saving and print preview.|Быстрый просмотрщик изображений и RAW для Windows с поворотом, сохранением и предпросмотром печати.|Ein schneller Windows-Bildbetrachter für Bilder und Kamera-RAW-Dateien, mit Drehen, Speichern und Druckvorschau.|Une visionneuse Windows rapide pour les images et fichiers RAW, avec rotation, enregistrement et aperçu avant impression.|Un visor rápido para Windows de imágenes y archivos RAW, con giro, guardado y vista previa de impresión.|Un visualizzatore Windows veloce per immagini e file RAW, con rotazione, salvataggio e anteprima di stampa.|Um visualizador rápido para Windows de imagens e ficheiros RAW, com rotação, gravação e pré-visualização de impressão.|Szybka przeglądarka obrazów i plików RAW dla Windows, z obrotem, zapisem i podglądem wydruku.|Швидкий переглядач зображень і RAW для Windows із поворотом, збереженням та попереднім переглядом друку.|快速的 Windows 图像与相机 RAW 查看器，支持旋转、保存和打印预览。
settings.version|Version {0}|Версия {0}|Version {0}|Version {0}|Versión {0}|Versione {0}|Versão {0}|Wersja {0}|Версія {0}|版本 {0}
settings.support.title|Support page|Страница поддержки|Unterstützungsseite|Page de soutien|Página de apoyo|Pagina di supporto|Página de apoio|Strona wsparcia|Сторінка підтримки|支持页面
settings.support.hint|No creator page is set by default. Add an HTTPS link to a creator page on Boosty, DonationAlerts, Donatty or Ko-fi, or leave this blank.|Страница автора пока не задана. Укажите HTTPS-ссылку на страницу автора в Boosty, DonationAlerts, Donatty или Ko-fi либо оставьте поле пустым.|Es ist keine Seite voreingestellt. Tragen Sie einen HTTPS-Link zu einer Autorenseite auf Boosty, DonationAlerts, Donatty oder Ko-fi ein, oder lassen Sie das Feld leer.|Aucune page n’est définie. Ajoutez un lien HTTPS vers une page de créateur sur Boosty, DonationAlerts, Donatty ou Ko-fi, ou laissez ce champ vide.|No hay página configurada. Añade un enlace HTTPS a una página de creador en Boosty, DonationAlerts, Donatty o Ko-fi, o déjalo vacío.|Nessuna pagina è preimpostata. Inserisci un link HTTPS a una pagina dell’autore su Boosty, DonationAlerts, Donatty o Ko-fi, oppure lascia vuoto.|Não está definida nenhuma página. Adicione uma ligação HTTPS para uma página de criador no Boosty, DonationAlerts, Donatty ou Ko-fi, ou deixe em branco.|Nie ustawiono strony autora. Dodaj link HTTPS do strony twórcy w Boosty, DonationAlerts, Donatty lub Ko-fi albo pozostaw pole puste.|Сторінку автора ще не задано. Вкажіть HTTPS-посилання на сторінку автора в Boosty, DonationAlerts, Donatty або Ko-fi чи залиште поле порожнім.|尚未设置创作者页面。可填写 Boosty、DonationAlerts、Donatty 或 Ko-fi 的创作者 HTTPS 链接，也可留空。
settings.support.open|Open page|Открыть страницу|Seite öffnen|Ouvrir la page|Abrir página|Apri pagina|Abrir página|Otwórz stronę|Відкрити сторінку|打开页面
settings.support.openError|Could not open the link: {0}|Не удалось открыть ссылку: {0}|Link konnte nicht geöffnet werden: {0}|Impossible d’ouvrir le lien : {0}|No se pudo abrir el enlace: {0}|Impossibile aprire il collegamento: {0}|Não foi possível abrir a ligação: {0}|Nie można otworzyć odnośnika: {0}|Не вдалося відкрити посилання: {0}|无法打开链接：{0}
settings.support.invalid|Use a valid HTTPS creator-page link on Boosty, DonationAlerts, Donatty or Ko-fi, or leave the field blank.|Нужна корректная HTTPS-ссылка на страницу автора в Boosty, DonationAlerts, Donatty или Ko-fi. Можно оставить поле пустым.|Verwenden Sie einen gültigen HTTPS-Link zu einer Autorenseite auf Boosty, DonationAlerts, Donatty oder Ko-fi, oder lassen Sie das Feld leer.|Utilisez un lien HTTPS valide vers une page de créateur sur Boosty, DonationAlerts, Donatty ou Ko-fi, ou laissez ce champ vide.|Usa un enlace HTTPS válido a una página de creador en Boosty, DonationAlerts, Donatty o Ko-fi, o deja el campo vacío.|Usa un link HTTPS valido a una pagina dell’autore su Boosty, DonationAlerts, Donatty o Ko-fi, oppure lascia vuoto.|Use uma ligação HTTPS válida para uma página de criador no Boosty, DonationAlerts, Donatty ou Ko-fi, ou deixe em branco.|Podaj poprawny link HTTPS do strony twórcy w Boosty, DonationAlerts, Donatty lub Ko-fi albo pozostaw pole puste.|Потрібне коректне HTTPS-посилання на сторінку автора в Boosty, DonationAlerts, Donatty або Ko-fi. Можна залишити поле порожнім.|请使用 Boosty、DonationAlerts、Donatty 或 Ko-fi 的有效创作者 HTTPS 链接，或留空。
help.title|Keyboard & mouse|Клавиатура и мышь|Tastatur und Maus|Clavier et souris|Teclado y ratón|Tastiera e mouse|Teclado e rato|Klawiatura i mysz|Клавіатура та миша|键盘与鼠标
help.keyboard|Keyboard shortcuts|Горячие клавиши|Tastenkürzel|Raccourcis clavier|Atajos de teclado|Scorciatoie da tastiera|Atalhos de teclado|Skróty klawiaturowe|Гарячі клавіші|键盘快捷键
help.shortcuts|Keyboard and mouse help|Справка по управлению|Hilfe zu Tastatur und Maus|Aide clavier et souris|Ayuda de teclado y ratón|Guida a tastiera e mouse|Ajuda de teclado e rato|Pomoc klawiatury i myszy|Довідка з керування|键盘与鼠标帮助
help.mouse|Mouse gestures|Жесты мышью|Mausgesten|Gestes de souris|Gestos del ratón|Gesti del mouse|Gestos do rato|Gesty myszy|Жести мишею|鼠标手势
help.open|Open an image|Открыть изображение|Bild öffnen|Ouvrir une image|Abrir una imagen|Apri un’immagine|Abrir uma imagem|Otwórz obraz|Відкрити зображення|打开图像
help.browse|Previous / next image|Предыдущее / следующее фото|Vorheriges / nächstes Bild|Image précédente / suivante|Imagen anterior / siguiente|Immagine precedente / successiva|Imagem anterior / seguinte|Poprzedni / następny obraz|Попереднє / наступне фото|上一张／下一张图像
help.zoom|Zoom out / in|Уменьшить / увеличить|Verkleinern / vergrößern|Réduire / agrandir|Alejar / acercar|Riduci / ingrandisci|Reduzir / ampliar|Pomniejsz / powiększ|Зменшити / збільшити|缩小／放大
help.fit|Fit the entire image|Вписать снимок целиком|Ganzes Bild einpassen|Afficher l’image entière|Ajustar la imagen completa|Adatta l’intera immagine|Ajustar a imagem inteira|Dopasuj cały obraz|Вписати знімок повністю|完整适应窗口
help.rotate|Rotate right / left by 90°|Повернуть вправо / влево на 90°|Um 90° nach rechts / links drehen|Tourner de 90° à droite / gauche|Girar 90° a la derecha / izquierda|Ruota di 90° a destra / sinistra|Rodar 90° à direita / esquerda|Obróć o 90° w prawo / lewo|Повернути праворуч / ліворуч на 90°|向右／向左旋转 90°
help.save|Save the rotation|Сохранить поворот|Drehung speichern|Enregistrer la rotation|Guardar el giro|Salva la rotazione|Guardar a rotação|Zapisz obrót|Зберегти поворот|保存旋转
help.saveCopy|Save a rotated copy|Сохранить повёрнутую копию|Gedrehte Kopie speichern|Enregistrer une copie tournée|Guardar una copia girada|Salva una copia ruotata|Guardar uma cópia rodada|Zapisz obróconą kopię|Зберегти повернуту копію|保存旋转后的副本
help.undo|Undo unsaved rotation|Отменить несохранённый поворот|Ungespeicherte Drehung rückgängig machen|Annuler la rotation non enregistrée|Deshacer el giro sin guardar|Annulla la rotazione non salvata|Anular a rotação não guardada|Cofnij niezapisany obrót|Скасувати незбережений поворот|撤销未保存的旋转
help.print|Open print preview|Открыть предпросмотр печати|Druckvorschau öffnen|Ouvrir l’aperçu avant impression|Abrir la vista previa de impresión|Apri l’anteprima di stampa|Abrir a pré-visualização de impressão|Otwórz podgląd wydruku|Відкрити попередній перегляд друку|打开打印预览
help.filmstrip|Show / hide thumbnails|Показать / скрыть ленту|Filmstreifen ein- / ausblenden|Afficher / masquer les vignettes|Mostrar / ocultar miniaturas|Mostra / nascondi miniature|Mostrar / ocultar miniaturas|Pokaż / ukryj miniatury|Показати / приховати стрічку|显示／隐藏缩略图
help.info|Show / hide image information|Показать / скрыть информацию|Bildinformationen ein- / ausblenden|Afficher / masquer les informations|Mostrar / ocultar información|Mostra / nascondi informazioni|Mostrar / ocultar informações|Pokaż / ukryj informacje|Показати / приховати інформацію|显示／隐藏图像信息
help.fullscreen|Enter / leave fullscreen|Войти / выйти из полного экрана|Vollbild ein- / ausschalten|Activer / quitter le plein écran|Entrar / salir de pantalla completa|Attiva / esci da schermo intero|Entrar / sair do ecrã inteiro|Włącz / wyłącz pełny ekran|Увійти / вийти з повного екрана|进入／退出全屏
help.escape|Leave fullscreen; otherwise close information and fit the image|Выйти из полного экрана; иначе скрыть информацию и вписать снимок|Vollbild verlassen; sonst Informationen schließen und Bild einpassen|Quitter le plein écran ; sinon fermer les informations et ajuster l’image|Salir de pantalla completa; si no, cerrar información y ajustar imagen|Esci da schermo intero; altrimenti chiudi le informazioni e adatta l’immagine|Sair do ecrã inteiro; caso contrário, fechar informações e ajustar a imagem|Wyjdź z pełnego ekranu; poza nim ukryj informacje i dopasuj obraz|Вийти з повного екрана; інакше приховати інформацію та вписати знімок|退出全屏；否则关闭信息并适应图像
help.wheel|Mouse wheel: zoom in or out.|Колесо мыши: изменить масштаб.|Mausrad: vergrößern oder verkleinern.|Molette : agrandir ou réduire.|Rueda del ratón: acercar o alejar.|Rotella del mouse: ingrandisci o riduci.|Roda do rato: ampliar ou reduzir.|Kółko myszy: powiększ lub pomniejsz.|Колесо миші: змінити масштаб.|鼠标滚轮：放大或缩小。
help.doubleClick|Double-click: switch between fit and 100%.|Двойной щелчок: переключить «вписать» и 100%.|Doppelklick: zwischen Einpassen und 100 % wechseln.|Double-clic : basculer entre l’ajustement et 100 %.|Doble clic: alternar entre ajustar y 100 %.|Doppio clic: passa tra adattamento e 100%.|Duplo clique: alternar entre ajustar e 100%.|Dwukrotne kliknięcie: przełącz dopasowanie i 100%.|Подвійне клацання: перемкнути «вписати» та 100%.|双击：在适应窗口与 100% 之间切换。
help.drag|Drag the fitted image sideways to browse. Drag a zoomed image to pan.|Тяните вписанный снимок в сторону, чтобы листать. Увеличенный снимок перетягивается внутри окна.|Eingepasstes Bild seitlich ziehen, um zu blättern; vergrößertes Bild ziehen, um es zu verschieben.|Glissez l’image ajustée latéralement pour changer d’image ; glissez une image agrandie pour la déplacer.|Arrastra lateralmente una imagen ajustada para navegar; arrastra una ampliada para desplazarla.|Trascina lateralmente l’immagine adattata per sfogliare; trascina un’immagine ingrandita per spostarla.|Arraste lateralmente a imagem ajustada para navegar; arraste uma imagem ampliada para a deslocar.|Przeciągnij dopasowany obraz w bok, aby przeglądać. Powiększony obraz można przesuwać.|Тягніть вписаний знімок убік, щоб гортати. Збільшений знімок можна пересувати у вікні.|横向拖动适应窗口的图像可切换照片；拖动放大的图像可平移。
help.stripDrag|Drag or scroll the thumbnail strip to browse it without changing the current photo. Click a thumbnail to open it.|Перетягивайте или прокручивайте ленту, не меняя текущий снимок. Щёлкните миниатюру, чтобы открыть её.|Filmstreifen ziehen oder scrollen, ohne das aktuelle Foto zu wechseln. Ein Vorschaubild zum Öffnen anklicken.|Faites glisser ou défiler les vignettes sans changer de photo. Cliquez sur une vignette pour l’ouvrir.|Arrastra o desplaza la tira sin cambiar la foto actual. Haz clic en una miniatura para abrirla.|Trascina o scorri le miniature senza cambiare la foto attuale. Fai clic su una miniatura per aprirla.|Arraste ou desloque a faixa sem mudar a fotografia atual. Clique numa miniatura para a abrir.|Przeciągaj lub przewijaj pasek bez zmiany zdjęcia. Kliknij miniaturę, aby ją otworzyć.|Перетягуйте чи прокручуйте стрічку, не змінюючи поточний знімок. Клацніть мініатюру, щоб відкрити її.|拖动或滚动缩略图条不会切换当前照片。单击缩略图即可打开。
help.drop|Drop image files into the window to open them.|Перетащите файлы изображений в окно, чтобы открыть их.|Bilddateien zum Öffnen in das Fenster ziehen.|Déposez des fichiers image dans la fenêtre pour les ouvrir.|Suelta archivos de imagen en la ventana para abrirlos.|Trascina file immagine nella finestra per aprirli.|Largue ficheiros de imagem na janela para os abrir.|Upuść pliki graficzne w oknie, aby je otworzyć.|Перетягніть файли зображень у вікно, щоб відкрити їх.|将图像文件拖入窗口即可打开。
print.title|Print — PhotoWoo|Печать — PhotoWoo|Drucken — PhotoWoo|Impression — PhotoWoo|Imprimir — PhotoWoo|Stampa — PhotoWoo|Imprimir — PhotoWoo|Drukowanie — PhotoWoo|Друк — PhotoWoo|打印 — PhotoWoo
print.heading|Print photograph|Печать фотографии|Foto drucken|Imprimer la photo|Imprimir fotografía|Stampa fotografia|Imprimir fotografia|Drukuj zdjęcie|Друк фотографії|打印照片
print.a4|A4 · 210 × 297 mm|A4 · 210 × 297 мм|A4 · 210 × 297 mm|A4 · 210 × 297 mm|A4 · 210 × 297 mm|A4 · 210 × 297 mm|A4 · 210 × 297 mm|A4 · 210 × 297 mm|A4 · 210 × 297 мм|A4 · 210 × 297 毫米
print.photoPaper|Photo · 10 × 15 cm|Фото · 10 × 15 см|Foto · 10 × 15 cm|Photo · 10 × 15 cm|Foto · 10 × 15 cm|Foto · 10 × 15 cm|Fotografia · 10 × 15 cm|Zdjęcie · 10 × 15 cm|Фото · 10 × 15 см|照片 · 10 × 15 厘米
print.portrait|Portrait|Книжная|Hochformat|Portrait|Vertical|Verticale|Vertical|Pionowa|Книжкова|纵向
print.landscape|Landscape|Альбомная|Querformat|Paysage|Horizontal|Orizzontale|Horizontal|Pozioma|Альбомна|横向
print.fit|Fit entire image|Вписать целиком|Ganzes Bild einpassen|Afficher l’image entière|Ajustar imagen completa|Adatta immagine intera|Ajustar a imagem inteira|Dopasuj cały obraz|Вписати повністю|完整适应页面
print.fill|Fill with cropping|Заполнить с обрезкой|Mit Beschnitt ausfüllen|Remplir en rognant|Llenar con recorte|Riempi ritagliando|Preencher com recorte|Wypełnij z przycięciem|Заповнити з обрізанням|裁切并填满
print.paper|Paper|Бумага|Papier|Papier|Papel|Carta|Papel|Papier|Папір|纸张
print.orientation|Orientation|Ориентация|Ausrichtung|Orientation|Orientación|Orientamento|Orientação|Orientacja|Орієнтація|方向
print.placement|Placement|Размещение|Platzierung|Disposition|Colocación|Posizionamento|Posicionamento|Rozmieszczenie|Розміщення|布局
print.cancel|Cancel|Отмена|Abbrechen|Annuler|Cancelar|Annulla|Cancelar|Anuluj|Скасувати|取消
print.choose|Choose printer…|Выбрать принтер…|Drucker auswählen…|Choisir l’imprimante…|Elegir impresora…|Scegli stampante…|Escolher impressora…|Wybierz drukarkę…|Вибрати принтер…|选择打印机…
print.send|Print|Печатать|Drucken|Imprimer|Imprimir|Stampa|Imprimir|Drukuj|Друкувати|打印
print.noPrinter|No printer selected|Принтер не выбран|Kein Drucker ausgewählt|Aucune imprimante sélectionnée|Ninguna impresora seleccionada|Nessuna stampante selezionata|Nenhuma impressora selecionada|Nie wybrano drukarki|Принтер не вибрано|未选择打印机
print.initialHint|Margins of at least 10 mm. Choose a printer to refine the paper size and printable area.\n\nNothing is sent until you click Print.|Поля от 10 мм. Выберите принтер: предпросмотр уточнит размер листа и доступную область печати.\n\nОтправка — только по кнопке «Печатать».|Ränder von mindestens 10 mm. Wählen Sie einen Drucker, um Papiergröße und Druckbereich zu präzisieren.\n\nGedruckt wird erst nach einem Klick auf Drucken.|Marges d’au moins 10 mm. Choisissez une imprimante pour préciser le papier et la zone imprimable.\n\nL’envoi a lieu uniquement avec Imprimer.|Márgenes de al menos 10 mm. Elige una impresora para ajustar el papel y el área imprimible.\n\nSolo se envía al pulsar Imprimir.|Margini di almeno 10 mm. Scegli una stampante per precisare carta e area stampabile.\n\nL’invio avviene solo facendo clic su Stampa.|Margens de pelo menos 10 mm. Escolha uma impressora para ajustar o papel e a área imprimível.\n\nSó é enviado ao clicar em Imprimir.|Marginesy co najmniej 10 mm. Wybierz drukarkę, aby ustalić papier i obszar wydruku.\n\nWysłanie nastąpi dopiero po kliknięciu Drukuj.|Поля від 10 мм. Виберіть принтер, щоб уточнити розмір паперу та область друку.\n\nНадсилання — лише кнопкою «Друкувати».|页边距至少为 10 毫米。选择打印机以确定纸张尺寸与可打印区域。\n\n仅在点击“打印”后才会发送任务。
print.preliminary|{0} · preliminary|{0} · предварительно|{0} · vorläufig|{0} · provisoire|{0} · provisional|{0} · provvisorio|{0} · provisório|{0} · wstępnie|{0} · попередньо|{0} · 初步预览
print.chooseAvailable|Choose an available printer.|Выберите доступный принтер.|Wählen Sie einen verfügbaren Drucker.|Choisissez une imprimante disponible.|Elige una impresora disponible.|Scegli una stampante disponibile.|Escolha uma impressora disponível.|Wybierz dostępną drukarkę.|Виберіть доступний принтер.|请选择可用的打印机。
print.copies|{0}\nCopies: {1}|{0}\nКопий: {1}|{0}\nExemplare: {1}|{0}\nCopies : {1}|{0}\nCopias: {1}|{0}\nCopie: {1}|{0}\nCópias: {1}|{0}\nKopie: {1}|{0}\nКопій: {1}|{0}\n份数：{1}
print.adjustedHint|The printer adjusted the settings. The preview is updated.\n\nCheck the placement, then click Print.|Принтер скорректировал параметры. Предпросмотр обновлён.\n\nПроверьте расположение фотографии и нажмите «Печатать».|Der Drucker hat Einstellungen angepasst. Die Vorschau wurde aktualisiert.\n\nPrüfen Sie die Platzierung und klicken Sie auf Drucken.|L’imprimante a ajusté les paramètres. L’aperçu est à jour.\n\nVérifiez la disposition, puis cliquez sur Imprimer.|La impresora ajustó la configuración. La vista previa está actualizada.\n\nComprueba la colocación y pulsa Imprimir.|La stampante ha corretto le impostazioni. L’anteprima è aggiornata.\n\nControlla il posizionamento e fai clic su Stampa.|A impressora ajustou as definições. A pré-visualização foi atualizada.\n\nVerifique o posicionamento e clique em Imprimir.|Drukarka zmieniła ustawienia. Podgląd został zaktualizowany.\n\nSprawdź rozmieszczenie i kliknij Drukuj.|Принтер скоригував параметри. Попередній перегляд оновлено.\n\nПеревірте розташування та натисніть «Друкувати».|打印机已调整设置，预览已更新。\n\n检查照片位置后，点击“打印”。
print.readyHint|The preview includes the printer’s margins and at least 10 mm of page margin.\n\nCheck the placement, then click Print.|Предпросмотр учитывает поля выбранного принтера и отступы от 10 мм.\n\nПроверьте расположение фотографии и нажмите «Печатать».|Die Vorschau berücksichtigt die Druckerränder und mindestens 10 mm Seitenrand.\n\nPrüfen Sie die Platzierung und klicken Sie auf Drucken.|L’aperçu inclut les marges de l’imprimante et au moins 10 mm de marge.\n\nVérifiez la disposition, puis cliquez sur Imprimer.|La vista previa incluye los márgenes de la impresora y al menos 10 mm de margen.\n\nComprueba la colocación y pulsa Imprimir.|L’anteprima include i margini della stampante e almeno 10 mm di margine pagina.\n\nControlla il posizionamento e fai clic su Stampa.|A pré-visualização inclui as margens da impressora e pelo menos 10 mm de margem.\n\nVerifique o posicionamento e clique em Imprimir.|Podgląd uwzględnia marginesy drukarki i co najmniej 10 mm marginesu strony.\n\nSprawdź rozmieszczenie i kliknij Drukuj.|Перегляд враховує поля вибраного принтера та відступи від 10 мм.\n\nПеревірте розташування та натисніть «Друкувати».|预览包含所选打印机的边距，以及至少 10 毫米的页边距。\n\n检查照片位置后，点击“打印”。
print.setupError|Could not configure printing|Не удалось настроить печать|Druckeinrichtung fehlgeschlagen|Impossible de configurer l’impression|No se pudo configurar la impresión|Impossibile configurare la stampa|Não foi possível configurar a impressão|Nie można skonfigurować wydruku|Не вдалося налаштувати друк|无法配置打印
print.mediaError|The driver did not report a paper size. Choose a size in printer properties and select the printer again.|Драйвер не сообщил размер бумаги. Укажите размер в свойствах принтера и повторите выбор.|Der Treiber meldet keine Papiergröße. Wählen Sie sie in den Druckereigenschaften und wählen Sie den Drucker erneut.|Le pilote n’a pas indiqué de format papier. Choisissez-en un dans les propriétés, puis resélectionnez l’imprimante.|El controlador no informó del tamaño del papel. Elígelo en las propiedades y selecciona de nuevo la impresora.|Il driver non ha indicato il formato carta. Sceglilo nelle proprietà e seleziona di nuovo la stampante.|O controlador não indicou o tamanho do papel. Escolha-o nas propriedades e volte a selecionar a impressora.|Sterownik nie podał rozmiaru papieru. Wybierz rozmiar we właściwościach i ponownie wybierz drukarkę.|Драйвер не повідомив розмір паперу. Вкажіть його у властивостях і знову виберіть принтер.|驱动程序未提供纸张尺寸。请在打印机属性中设置尺寸，然后重新选择打印机。
print.areaError|The driver did not report a printable area. Check the paper and printer settings.|Драйвер не сообщил доступную область печати. Проверьте бумагу и параметры принтера.|Der Treiber meldet keinen Druckbereich. Prüfen Sie Papier und Druckereinstellungen.|Le pilote n’a pas indiqué de zone imprimable. Vérifiez le papier et les paramètres.|El controlador no informó del área imprimible. Comprueba el papel y los ajustes.|Il driver non ha indicato l’area stampabile. Controlla carta e impostazioni.|O controlador não indicou a área imprimível. Verifique o papel e as definições.|Sterownik nie podał obszaru wydruku. Sprawdź papier i ustawienia drukarki.|Драйвер не повідомив доступну область друку. Перевірте папір і параметри принтера.|驱动程序未提供可打印区域。请检查纸张和打印机设置。
print.noArea|These settings leave no printable area.|Для выбранных параметров нет доступной области печати.|Mit diesen Einstellungen ist kein Druckbereich verfügbar.|Ces paramètres ne laissent aucune zone imprimable.|Estos ajustes no dejan área imprimible.|Queste impostazioni non lasciano un’area stampabile.|Estas definições não deixam área imprimível.|Te ustawienia nie pozostawiają obszaru wydruku.|Для вибраних параметрів немає доступної області друку.|当前设置没有可用的打印区域。
print.fromPrinter|From printer · {0}|Из принтера · {0}|Vom Drucker · {0}|De l’imprimante · {0}|De la impresora · {0}|Dalla stampante · {0}|Da impressora · {0}|Z drukarki · {0}|З принтера · {0}|来自打印机 · {0}
print.tooSmall|The paper is too small for a photograph with 10 mm margins.|Бумага слишком мала для фотографии с полями 10 мм.|Das Papier ist für ein Foto mit 10 mm Rand zu klein.|Le papier est trop petit pour une photo avec des marges de 10 mm.|El papel es demasiado pequeño para una foto con márgenes de 10 mm.|La carta è troppo piccola per una foto con margini di 10 mm.|O papel é demasiado pequeno para uma fotografia com margens de 10 mm.|Papier jest za mały na zdjęcie z marginesami 10 mm.|Папір замалий для фотографії з полями 10 мм.|纸张太小，无法容纳带 10 毫米边距的照片。
print.sendError|Could not send to printer|Не удалось отправить на печать|Druckauftrag konnte nicht gesendet werden|Impossible d’envoyer l’impression|No se pudo enviar a la impresora|Impossibile inviare alla stampante|Não foi possível enviar para a impressora|Nie można wysłać do drukarki|Не вдалося надіслати на друк|无法发送到打印机
print.size|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} мм|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} mm|{0:0.#} × {1:0.#} мм|{0:0.#} × {1:0.#} 毫米
""";
}
