namespace PhotoWoo.Localization;

public static class UpdateTranslations
{
    public static void Register()
    {
        string[] languages = ["en", "ru", "de", "fr", "es", "it", "pt", "pl", "uk", "zh-Hans"];
        var translations = languages.ToDictionary(code => code, _ => new Dictionary<string, string>(StringComparer.Ordinal));
        foreach (var row in Rows.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var fields = row.Split('|');
            if (fields.Length != languages.Length + 1) throw new InvalidOperationException("Incomplete update translation: " + fields[0]);
            for (var i = 0; i < languages.Length; i++) translations[languages[i]].Add(fields[0], fields[i + 1]);
        }
        foreach (var (language, entries) in translations) L10n.RegisterTranslations(language, entries);
    }

    private const string Rows = """
settings.tab.updates|Updates|Обновления|Updates|Mises à jour|Actualizaciones|Aggiornamenti|Atualizações|Aktualizacje|Оновлення|更新
updates.installedVersion|Installed version {0}|Установлена версия {0}|Installierte Version {0}|Version installée : {0}|Versión instalada: {0}|Versione installata: {0}|Versão instalada: {0}|Zainstalowana wersja: {0}|Встановлено версію {0}|已安装版本 {0}
updates.autoCheck|Check for updates automatically|Проверять обновления автоматически|Automatisch nach Updates suchen|Rechercher automatiquement les mises à jour|Buscar actualizaciones automáticamente|Cerca aggiornamenti automaticamente|Procurar atualizações automaticamente|Automatycznie sprawdzaj aktualizacje|Перевіряти оновлення автоматично|自动检查更新
updates.autoCheckHint|Check at startup and every 30 minutes while PhotoWoo is open.|Проверять при запуске и каждые 30 минут, пока PhotoWoo открыт.|Beim Start und alle 30 Minuten prüfen, solange PhotoWoo geöffnet ist.|Vérifier au démarrage, puis toutes les 30 minutes tant que PhotoWoo est ouvert.|Comprobar al iniciar y cada 30 minutos mientras PhotoWoo esté abierto.|Controlla all’avvio e ogni 30 minuti mentre PhotoWoo è aperto.|Verificar ao iniciar e a cada 30 minutos enquanto o PhotoWoo estiver aberto.|Sprawdzaj przy uruchomieniu i co 30 minut, gdy PhotoWoo jest otwarty.|Перевіряти під час запуску та кожні 30 хвилин, поки PhotoWoo відкрито.|启动时检查，并在 PhotoWoo 打开期间每 30 分钟检查一次。
updates.check|Check for updates|Проверить обновления|Nach Updates suchen|Rechercher des mises à jour|Buscar actualizaciones|Cerca aggiornamenti|Procurar atualizações|Sprawdź aktualizacje|Перевірити оновлення|检查更新
updates.settingsDescription|Updates come from published stable GitHub Releases. You choose when to download and install; PhotoWoo will not restart without confirmation.|Обновления поступают из опубликованных стабильных релизов на GitHub. Вы выбираете, когда скачать и установить их; PhotoWoo не перезапускается без подтверждения.|Updates stammen aus veröffentlichten stabilen GitHub-Releases. Sie entscheiden über Download und Installation; PhotoWoo startet nicht ohne Bestätigung neu.|Les mises à jour proviennent des versions stables publiées sur GitHub. Vous choisissez quand les télécharger et les installer ; PhotoWoo ne redémarre pas sans confirmation.|Las actualizaciones provienen de versiones estables publicadas en GitHub. Tú decides cuándo descargarlas e instalarlas; PhotoWoo no se reinicia sin confirmación.|Gli aggiornamenti provengono dalle versioni stabili pubblicate su GitHub. Scegli tu quando scaricarli e installarli; PhotoWoo non si riavvia senza conferma.|As atualizações vêm de versões estáveis publicadas no GitHub. Escolhe quando transferir e instalar; o PhotoWoo não reinicia sem confirmação.|Aktualizacje pochodzą ze stabilnych wydań opublikowanych na GitHubie. Ty wybierasz, kiedy je pobrać i zainstalować; PhotoWoo nie uruchomi się ponownie bez potwierdzenia.|Оновлення надходять з опублікованих стабільних випусків на GitHub. Ви обираєте, коли завантажити та встановити їх; PhotoWoo не перезапускається без підтвердження.|更新来自 GitHub 上发布的稳定版本。您决定何时下载和安装；未经确认，PhotoWoo 不会重启。
updates.title|PhotoWoo updates|Обновления PhotoWoo|PhotoWoo-Updates|Mises à jour de PhotoWoo|Actualizaciones de PhotoWoo|Aggiornamenti di PhotoWoo|Atualizações do PhotoWoo|Aktualizacje PhotoWoo|Оновлення PhotoWoo|PhotoWoo 更新
updates.checking|Checking for updates…|Проверка обновлений…|Updates werden gesucht…|Recherche de mises à jour…|Buscando actualizaciones…|Ricerca aggiornamenti…|A procurar atualizações…|Sprawdzanie aktualizacji…|Перевірка оновлень…|正在检查更新…
updates.upToDate|You have the latest version.|У вас последняя версия.|Sie verwenden die neueste Version.|Vous disposez de la dernière version.|Tienes la última versión.|Hai già l’ultima versione.|Tem a versão mais recente.|Masz najnowszą wersję.|У вас найновіша версія.|您已使用最新版本。
updates.available|PhotoWoo {0} is available|Доступен PhotoWoo {0}|PhotoWoo {0} ist verfügbar|PhotoWoo {0} est disponible|PhotoWoo {0} está disponible|PhotoWoo {0} è disponibile|PhotoWoo {0} está disponível|Dostępny jest PhotoWoo {0}|Доступний PhotoWoo {0}|PhotoWoo {0} 现已可用
updates.releaseInfo|Installed: {0} · Download: {1:N1} MB|Установлено: {0} · Загрузка: {1:N1} МБ|Installiert: {0} · Download: {1:N1} MB|Installée : {0} · Téléchargement : {1:N1} Mo|Instalada: {0} · Descarga: {1:N1} MB|Installata: {0} · Download: {1:N1} MB|Instalada: {0} · Transferência: {1:N1} MB|Zainstalowano: {0} · Pobieranie: {1:N1} MB|Встановлено: {0} · Завантаження: {1:N1} МБ|已安装：{0} · 下载大小：{1:N1} MB
updates.download|Download update|Скачать обновление|Update herunterladen|Télécharger la mise à jour|Descargar actualización|Scarica aggiornamento|Transferir atualização|Pobierz aktualizację|Завантажити оновлення|下载更新
updates.downloading|Downloading… {0:N0}%|Загрузка… {0:N0}%|Wird heruntergeladen… {0:N0}%|Téléchargement… {0:N0}%|Descargando… {0:N0}%|Download… {0:N0}%|A transferir… {0:N0}%|Pobieranie… {0:N0}%|Завантаження… {0:N0}%|正在下载… {0:N0}%
updates.verifying|Verifying download…|Проверка загруженного файла…|Download wird überprüft…|Vérification du téléchargement…|Verificando descarga…|Verifica del download…|A verificar a transferência…|Sprawdzanie pobranego pliku…|Перевірка завантаженого файлу…|正在验证下载文件…
updates.extracting|Preparing update…|Подготовка обновления…|Update wird vorbereitet…|Préparation de la mise à jour…|Preparando actualización…|Preparazione dell’aggiornamento…|A preparar a atualização…|Przygotowywanie aktualizacji…|Підготовка оновлення…|正在准备更新…
updates.ready|Ready to install. PhotoWoo will close briefly and restart.|Готово к установке. PhotoWoo ненадолго закроется и запустится снова.|Bereit zur Installation. PhotoWoo wird kurz geschlossen und neu gestartet.|Prêt pour l’installation. PhotoWoo se fermera brièvement, puis redémarrera.|Listo para instalar. PhotoWoo se cerrará brevemente y volverá a abrirse.|Pronto per l’installazione. PhotoWoo si chiuderà brevemente e si riavvierà.|Pronto para instalar. O PhotoWoo fecha por instantes e reinicia.|Gotowe do instalacji. PhotoWoo zamknie się na chwilę i uruchomi ponownie.|Готово до встановлення. PhotoWoo ненадовго закриється та запуститься знову.|已准备好安装。PhotoWoo 将短暂关闭并重新启动。
updates.install|Install and restart|Установить и перезапустить|Installieren und neu starten|Installer et redémarrer|Instalar y reiniciar|Installa e riavvia|Instalar e reiniciar|Zainstaluj i uruchom ponownie|Встановити та перезапустити|安装并重启
updates.later|Later|Позже|Später|Plus tard|Más tarde|Più tardi|Mais tarde|Później|Пізніше|稍后
updates.cancel|Cancel download|Отменить загрузку|Download abbrechen|Annuler le téléchargement|Cancelar descarga|Annulla download|Cancelar transferência|Anuluj pobieranie|Скасувати завантаження|取消下载
updates.cancelled|Download cancelled. You can try again.|Загрузка отменена. Можно повторить попытку.|Download abgebrochen. Sie können es erneut versuchen.|Téléchargement annulé. Vous pouvez réessayer.|Descarga cancelada. Puedes volver a intentarlo.|Download annullato. Puoi riprovare.|Transferência cancelada. Pode tentar novamente.|Pobieranie anulowane. Możesz spróbować ponownie.|Завантаження скасовано. Можна спробувати знову.|下载已取消。您可以重试。
updates.checkFailed|Could not check for updates. Check your connection and try again.|Не удалось проверить обновления. Проверьте подключение и повторите попытку.|Updates konnten nicht geprüft werden. Prüfen Sie die Verbindung und versuchen Sie es erneut.|Impossible de rechercher les mises à jour. Vérifiez votre connexion et réessayez.|No se pudieron buscar actualizaciones. Comprueba la conexión y vuelve a intentarlo.|Impossibile cercare aggiornamenti. Controlla la connessione e riprova.|Não foi possível procurar atualizações. Verifique a ligação e tente novamente.|Nie można sprawdzić aktualizacji. Sprawdź połączenie i spróbuj ponownie.|Не вдалося перевірити оновлення. Перевірте з’єднання та спробуйте знову.|无法检查更新。请检查连接后重试。
updates.failed|Update could not be completed. Your current version is still available.|Не удалось завершить обновление. Текущая версия остаётся доступной.|Das Update konnte nicht abgeschlossen werden. Ihre aktuelle Version ist weiterhin verfügbar.|La mise à jour n’a pas pu être terminée. Votre version actuelle reste disponible.|No se pudo completar la actualización. Tu versión actual sigue disponible.|Impossibile completare l’aggiornamento. La versione attuale resta disponibile.|Não foi possível concluir a atualização. A versão atual continua disponível.|Nie można ukończyć aktualizacji. Obecna wersja jest nadal dostępna.|Не вдалося завершити оновлення. Поточна версія залишається доступною.|无法完成更新。您仍可使用当前版本。
updates.retry|Try again|Повторить|Erneut versuchen|Réessayer|Reintentar|Riprova|Tentar novamente|Spróbuj ponownie|Повторити|重试
updates.releaseNotes|What’s new|Что нового|Was ist neu?|Nouveautés|Novedades|Novità|Novidades|Co nowego|Що нового|更新内容
updates.openRelease|View release on GitHub|Открыть релиз на GitHub|Release auf GitHub ansehen|Voir la version sur GitHub|Ver versión en GitHub|Vedi versione su GitHub|Ver versão no GitHub|Zobacz wydanie na GitHubie|Відкрити випуск на GitHub|在 GitHub 查看此版本
updates.confirm|Download and installation only start after your confirmation. Photos and settings are preserved.|Загрузка и установка начинаются только после вашего подтверждения. Фотографии и настройки сохраняются.|Download und Installation beginnen erst nach Ihrer Bestätigung. Fotos und Einstellungen bleiben erhalten.|Le téléchargement et l’installation ne commencent qu’après votre confirmation. Photos et paramètres sont conservés.|La descarga y la instalación solo comienzan tras tu confirmación. Las fotos y los ajustes se conservan.|Download e installazione iniziano solo dopo la tua conferma. Foto e impostazioni vengono conservate.|A transferência e a instalação só começam após a sua confirmação. As fotografias e definições são preservadas.|Pobieranie i instalacja rozpoczynają się dopiero po Twoim potwierdzeniu. Zdjęcia i ustawienia zostają zachowane.|Завантаження та встановлення починаються лише після вашого підтвердження. Фотографії та налаштування зберігаються.|下载和安装仅在您确认后开始。照片和设置会予以保留。
updates.installBlocked|Close other copies of PhotoWoo before updating.|Перед обновлением закройте другие окна PhotoWoo.|Schließen Sie vor dem Update weitere PhotoWoo-Instanzen.|Fermez les autres instances de PhotoWoo avant la mise à jour.|Cierra las demás instancias de PhotoWoo antes de actualizar.|Chiudi le altre istanze di PhotoWoo prima di aggiornare.|Feche as outras instâncias do PhotoWoo antes de atualizar.|Przed aktualizacją zamknij pozostałe instancje PhotoWoo.|Перед оновленням закрийте інші вікна PhotoWoo.|更新前请关闭其他 PhotoWoo 实例。
updates.success|Updated to PhotoWoo {0}.|Обновлено до PhotoWoo {0}.|Auf PhotoWoo {0} aktualisiert.|Mise à jour vers PhotoWoo {0} terminée.|Actualizado a PhotoWoo {0}.|Aggiornato a PhotoWoo {0}.|Atualizado para PhotoWoo {0}.|Zaktualizowano do PhotoWoo {0}.|Оновлено до PhotoWoo {0}.|已更新至 PhotoWoo {0}。
updates.installing|Starting update…|Запуск обновления…|Update wird gestartet…|Démarrage de la mise à jour…|Iniciando actualización…|Avvio dell’aggiornamento…|A iniciar a atualização…|Uruchamianie aktualizacji…|Запуск оновлення…|正在开始更新…
updates.unsupported|Automatic installation is unavailable in this folder. Download the release from GitHub.|Автоматическая установка в эту папку недоступна. Скачайте релиз с GitHub.|Die automatische Installation ist in diesem Ordner nicht verfügbar. Laden Sie die Version von GitHub herunter.|L’installation automatique n’est pas disponible dans ce dossier. Téléchargez la version depuis GitHub.|La instalación automática no está disponible en esta carpeta. Descarga la versión desde GitHub.|L’installazione automatica non è disponibile in questa cartella. Scarica la versione da GitHub.|A instalação automática não está disponível nesta pasta. Transfira a versão do GitHub.|Automatyczna instalacja w tym folderze jest niedostępna. Pobierz wydanie z GitHuba.|Автоматичне встановлення в цю папку недоступне. Завантажте випуск із GitHub.|无法在此文件夹中自动安装。请从 GitHub 下载该版本。
updates.notice|Update available · {0}|Доступно обновление · {0}|Update verfügbar · {0}|Mise à jour disponible · {0}|Actualización disponible · {0}|Aggiornamento disponibile · {0}|Atualização disponível · {0}|Dostępna aktualizacja · {0}|Доступне оновлення · {0}|有可用更新 · {0}
updates.button|Update|Обновить|Aktualisieren|Mettre à jour|Actualizar|Aggiorna|Atualizar|Aktualizuj|Оновити|更新
updates.manualHint|Automatic checks run at startup and every 30 minutes. Nothing is installed without confirmation.|Автоматическая проверка выполняется при запуске и каждые 30 минут. Ничего не устанавливается без подтверждения.|Automatische Prüfungen erfolgen beim Start und alle 30 Minuten. Ohne Bestätigung wird nichts installiert.|La recherche automatique a lieu au démarrage, puis toutes les 30 minutes. Rien n’est installé sans confirmation.|La búsqueda automática se realiza al iniciar y cada 30 minutos. No se instala nada sin confirmación.|Il controllo automatico avviene all’avvio e ogni 30 minuti. Nulla viene installato senza conferma.|A verificação automática ocorre ao iniciar e a cada 30 minutos. Nada é instalado sem confirmação.|Automatyczne sprawdzanie odbywa się przy uruchomieniu i co 30 minut. Nic nie jest instalowane bez potwierdzenia.|Автоматична перевірка виконується під час запуску та кожні 30 хвилин. Нічого не встановлюється без підтвердження.|启动时及每 30 分钟自动检查一次。未经确认，不会安装任何内容。
""";
}
